name: Deployment
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on:
      - self-hosted
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: set up jdk 11
        uses: actions/setup-java@v1
        with:
          java-version: 11      
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2                   
      - name: build and package project
        run: mvn -f pom.xml clean package
      - name: show contents of current working directory
        run: dir
      - name: show contents of target directory
        run: dir target  
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: ./target/helloworld.war  
      - name: move war file 
        run: |
          New-Item -ItemType Directory -Path //wjbdevls1/Tomcat9.0.62/webapps/helloworld
          Copy-Item ./target/helloworld.war //wjbdevls1/Tomcat9.0.62/webapps/helloworld            
          #New-Item -ItemType Directory -Path C:/apache-tomcat-9.0.26/webapps/helloworld
          #Copy-Item ./target/helloworld.war C:/apache-tomcat-9.0.26/webapps/helloworld  
          #\\wjbdevls1\Tomcat9.0.62\webapps    

  deploy:
    needs: build
    runs-on:
      - self-hosted
    steps:
      - name: set up jdk 11
        uses: actions/setup-java@v1
        with:
          java-version: 11      
      - name: explode war file
        #working-directory: C:/apache-tomcat-9.0.26/webapps/helloworld
        working-directory: //wjbdevls1/Tomcat9.0.62/webapps/helloworld
        run: |
          jar -xvf helloworld.war
          Remove-Item helloworld.war            
          

                 